"""Add index

Revision ID: a22587072548
Revises: 37220ed9a957
Create Date: 2025-01-28 21:14:16.095422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22587072548'
down_revision: Union[str, None] = '37220ed9a957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_counters_sender_name'), 'user_counters', ['sender_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_counters_sender_name'), table_name='user_counters')
    # ### end Alembic commands ###
